then & catch()

promise.then (Cres) => { ... })

promise.catch((err)) => {...})
